installation:
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    nodeAddressAutodetectionV4:
      interface: enp3s0
    ipPools:
      - name: default-ipv4-ippool
        cidr: 10.244.0.0/16
        blockSize: 26
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()
