apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    gateway-access: "true"                          # Grafana נחשף דרך ה-Gateway
    pod-security.kubernetes.io/enforce: privileged  # node-exporter צריך גישה ל-host
    pod-security.kubernetes.io/warn: privileged
