---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: concretetrack-db-app
  namespace: concretetrack
spec:
  encryptedData:
    password: AgBMhf17HS4TrgTt4Y5JNiwf83oo8VTsCBpuZoWTsSeA9Ai4L2LI3I9/8YgQhpSB8rPGWszNwbF4gjvonHwfmBUq8CFvWjhuNxbpsUF37R5JJocO2O19jkpVIl64/30N1iAqMgX6I1deQmKEyQevP14c+5cfq0MiHfHQPssGtFu3M8t5GsWQjzYQawPprpVDW/qQxQtj2eGqxG8J69XYOmMr59ZlncQZ40cKUTpzS0Kfev4wASHk+Eze6jwZTqaRVhjmsdOgnRSw1ggbfELxzvAtX10v2Ls5ek77NXLFYln+NGbcd8JTBl4tu/jckvsbRtU0At7EOJPsEzMlTjpM/V7lR+bsYP0oj/a2mL6bjVxzB5WQeMN3YWqbl+823b/le8/1CmoPw2z/QhhK7ekgAeVJLm+2iBSTccTtlcRf1zt3OFZMfytqZ85rBD6rJI0XJqWc4YGjqV62VTv/IcagVX8G3WM2vN/k6PLrVDjYF7q53siZTPRHoan0Txlm4nAilVtD2K5x1cz4cA1RB8nHmJcKDUFFxClEokUGLsR7imfJkXLZtlUb11+LgPoHc9tg/FCbyItIxB21oYMUNiEdhsBftHo+Yw93n+uvamkJiHWKoJtUMIE2yxFq540RMt1+m5czYLL6FBtKdvtGnZyNibDqLZQJ+/qSMI1uhe2wEheVFXEd1VF3aVeaQBjqnAd4oOhlWe2/q92GsVVU0srNhY0ukzou+NUqYh3vyENgFG5JJPhHC8TyZfoMiMnSEl0Fhog=
    username: AgCqN1sa5v430KfmKuFrGKPhV+FzeC8s3jS4y5oFbnsyxDAaKiJu0vdkRU7BooPHOoBq6msp9v6i2eYCaoxE74sFVjN+mi7MU9NA3k+WnBtOxW0GoCvueSRKQK2J49e3lHknk9ySJpNvnPXFR7ZhfDK/A6UHJB3hM8KqvZsnmaUrjY5x4M/iS40ufMrkaDw/q7cvHc/O53NGSMzEvI5l7VMd2SvdgAWusjDllDH1MAGsyIUhssgco+j8qofClLuirNXxC8XekrlTC7cV1Lj/MceegDpMLfTbLMCgcN1ffKP2J5TNSxC4qOXd0/CXuHb4HsehyRmZtc33i2B7NEUNM9ly9JVqW9GWX3c1ig302/gI37shp5wBuzXhqznfpoP6A179Fm8zUTUMLwsbQU6VtiYbLD6sFkcrOFr7uPgoErisNoTjWjUMLVF4HuZ5S+GfWmRGLVwtDNTQ5wiCg/zOoZOndT60ESXVMgQ3x3sU/jPik8poO1kDrJow02ymvlJrwbcx7FzCxZhvOHn576JqgHYu1dSrHEwW+soaec+ymehaQpXZIJc709jJpV09lpe3RL+p48Rr6p/rXrZKEBOyAU/LLK0YqbeIJyVX+94igGpjMplITSwlgT5X1muCCJ+7ByuGnvwyS04wQDLkSgfuw+UfEycqFjYJxpAnvHScSdDWurBLUxssvL/C9za8i10NjPSmlqEVGSpLp4yXNo5b
  template:
    metadata:
      name: concretetrack-db-app
      namespace: concretetrack
    type: kubernetes.io/basic-auth
