---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBYoqZBMjyV/mnMBPBBbdm6zhq3g4y5a9jBKG/TYStXAT0N2Nt+ZeVUyxy5O+cM5OFYFFCtl1KqJ8ccuFE8CUwlk44JbaC4pLPq1WmT6MzCrN3dvLyOhJLE7cp567JQY/Cdu5FWUNKjqAm81c9tXG2ALoUe4dDPIYBVdarp71ToNNSrd2dfCxi+5TBNsNbCSVaFq1kxlc6yIGMoCF+Qi15W3MvxwZ/HjVeyssEZ2jhhd3ImHJVBYywfkZCE11g+jA5VLe2v/JTNnKdOP+dLpAJ26nKEAM7NuxGM4LasKfinteofApjJ+F60qJCXOX/LhclwYooxL9ODgC9123civFbrffen9VpyKZ0PhqWhj8SQNCqV5jNe66AJaKrhdbjMYz/gAMaw/Z8I6MOVLsqxYF0UvSGSO6+nBXU4I9rM7AhLfsTFZjXY1A2U64KEXxy3lQT++SgTHQGdR++pkVIJEg+amXfLil7xPEOETQgtUOnNU3xJIAb7WFxEsvdbRxPPYMqwm15szHq4vsj4XUrwuycSwbO+TSNB7BrXR7CVmD8hr35I6N2WdwDep+UTnJu+NmhjRtOaY0WFnd+FD4/O0H4K+98R3ZxNBo1YZ+6Ho/lT3YZZAvyK1im6HsKefC9oT8lERuLCPukJlR6YIsdyt4gkWrgEV2hA7fcgl4uUT0dnpgYTxvfH/uig+b2JhLIN1t3eZKBNiQ9dOmgdA3mMMEMMp9Olhw==
    admin-user: AgBEhmXDrkrAf6zgOArrU120gNpYd2TaQRnwWWYoqUJHglYdweT+tcVm4l9gbt9IQQGivJ9nwKUz7QeQNmBmYZG4SerSiRpVVx/O5MLlrQPV7Lgbp0U/gg3SjDvPVbeTqXQjcrtxwn6GrWzfTqoNU49UU0iT69Mz99V6tC6xMOPg0eKtDpJDlEy3JB6Y9/Fp4MMc2ox3qQoVjCVyINLY7w4PRVRhbnd1PdqEzZ2TuQAXSiAjW686sPrbRTacLU7uEmppXcyGn1nacIN/i0qZ4MnxdHH2ulj08dkt1GkXyAB74yvDKGRX0IcbA2ju+T9nNYGzlIx83K1SRZOmhP20s4Bne4CYm8bbjOSdJ7A9GGvubpUwkqp3+8ROawvhD5Z5aV5dtUk46CIbLYcj9KKn+lMSUXY3plRIKYzddacBzmbkBBKEauQWzBQ42I9oILTrGYv09VthszXw34118vc5hvSoN0cQ4yJaUy3jrUfrs/gQ86ZC93flDXDrzqlGf7ry//93QKlGKjG6R7W4wkLACRozBd5TIKNJDPxguaVhglHNo9MskO95AZ0B/zPBVNN5VFuz/EFC9GRFnGk0yBy8UaLYgRVMUckERQvJ9j1b/4F4N0HbzIJvbVkXQaOWbqH1578G3h0peAaGYGh+zMtZdOSFwfRJeYrAKgUyUyzt1g4mMmv6L1uJRY91xK+aw/OZC7N79q4aYQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
